name: news_app
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.1.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.0
  animated_custom_dropdown: ^3.1.1
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  generate: true

  uses-material-design: true


  assets:
   - assets/images/
   - assets/icons/


  fonts:
    - family: Exo
      fonts:
       - asset: assets/fonts/Exo-Bold.ttf
       - asset: assets/fonts/Exo-Medium.ttf
       - asset: assets/fonts/Exo-Regular.ttf
       - asset: assets/fonts/Exo-SemiBold.ttf


